### ISSUE TITLE
Early Combos PR got merged

### ISSUE THREAD

**Issue by carcinization** [precondition/precondition.github.io#21]
Hi precondition!

The Early Combos PR in QMK got merged into QMK:Develop very recently. Since a lot of people refer to your Home Row Mods guide, and it mentions sevanteri's early combos, could you please add an update letting people know they can just fork QMK:Develop instead now?

This is mostly important to me because merging that repo was a PITA before, and I want to save other people the trouble haha. Thanks so much for your hard work on this invaluable guide!

**Comment by precondition** [comment]
Solved in https://github.com/precondition/precondition.github.io/commit/e683b12e4ae9fca236a1e923da6469e3b0193998
