### ISSUE TITLE
Broken image in blog post

### ISSUE THREAD

**Issue by nkempe** [precondition/precondition.github.io#28]
https://github.com/precondition/precondition.github.io/blob/9a7c78bf12c5865955d0365af2f35128ca2559d0/_posts/2020-11-01-home-row-mods.md?plain=1#L38

The image after the first paragraph in the article "A guide to home row mods" on https://precondition.github.io/home-row-mods is missing.
Fortunately you did provide a perfect alt-text, which makes it very clear to humans and machines what the image is/was about. Thank you for that. :)

**Comment by precondition** [comment]
Thank you for the heads-up
